# Generated by Django 2.1.3 on 2018-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region_id', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('rating_counter', models.IntegerField(default=0)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city_id', models.IntegerField(default=0)),
                ('tel', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=200)),
                ('brand_id', models.IntegerField(default=0)),
            ],
        ),
    ]
