# Generated by Django 2.1.3 on 2018-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
