# Generated by Django 2.1.3 on 2018-11-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feature_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='price',
        ),
        migrations.AddField(
            model_name='fuel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
