# Generated by Django 2.1.3 on 2018-11-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181126_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='station',
            name='fuel_id',
        ),
        migrations.AddField(
            model_name='stationfuel',
            name='fuel',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Fuel'),
        ),
        migrations.AddField(
            model_name='stationfuel',
            name='station',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Station'),
        ),
    ]
